### ISSUE TITLE
Some questions about KTMR

### ISSUE THREAD

**Issue by Tatuxuan** [BITwzl/KTMR#2]
Hello, may I ask what is the matrix code for the masks/240/10.mat file in JSON? I couldn't find a specific generation method in the source code

**Comment by BITwzl** [comment]
The masks are not uploaded as it's not related to the model. It's free to use any masks, and we provide ours here just as a backup.
[masks.zip](https://github.com/BITwzl/KTMR/files/15284113/masks.zip)
